name: camera_marker
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #GETX
  get: 

  #http
  dio: 4.0.0  

  uuid: 3.0.4
    
  #loading
  flutter_spinkit: 5.0.0

  shared_preferences: 2.0.6
  camera: 0.9.4+19
  permission_handler: 6.0.0
  rxdart: 0.27.1
  cupertino_icons: 1.0.2
  path_provider: 2.0.2
  flutter_downloader: 1.6.1
  share: 2.0.4
  intl: 0.17.0
  flutter_datetime_picker: 1.5.1
  pie_chart: 5.0.0
  excel: 2.0.0-null-safety-3
  archive: 3.1.2
  syncfusion_flutter_xlsio: 19.2.62-beta
  package_info:
  url_launcher: 6.0.9
  flutter_ringtone_player: ^3.0.0

  #firebase
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/asset/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
